<?php
// DO NOT EDIT THIS FILE. IT WILL BE AUTO-GENERATE ITSELF FROM TIME TO TIME.

use App\Helpers\Screen;

Route::any("/test", function () {
    $process = Screen::get()->executeFileNow(base_path("shell_scripts/create_new_user.shell"), ["nawazthegreat", "udfsyhsduif&&@&#"], null, 20);
    dd($process);
});
